import {
  Settings,
  FileText,
  ImageIcon,
  FileImage,
  QrCode,
  Signature,
  Calculator,
  MailCheck,
  ShieldCheck,
  Megaphone,
  MessageSquareText,
  NotebookTabs,
  GraduationCap,
} from 'lucide-react'
import type { AppDefinition, AppRole } from './types'

export const apps: AppDefinition[] = [
  {
    id: 'settings',
    name: 'Configuración',
    description: 'Perfil, organización, apariencia y notificaciones.',
    icon: Settings,
    href: '/app/settings',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'pdf-workbench',
    name: 'PDF Workbench',
    description: 'Combinar, separar, reordenar y editar páginas de PDFs. Todo en tu navegador, nada se sube.',
    icon: FileText,
    href: '/app/tools/pdf-workbench',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'image-converter',
    name: 'Conversor de imágenes',
    description: 'Convertir entre PNG, JPG y WebP, redimensionar y comprimir. Todo en tu navegador, nada se sube.',
    icon: FileImage,
    href: '/app/tools/image-converter',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'qr-generator',
    name: 'Generador de QR',
    description: 'Códigos QR para URLs, vCard, WiFi y texto. Descargá en PNG o SVG.',
    icon: QrCode,
    href: '/app/tools/qr-generator',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'pdf-sign',
    name: 'Firma de PDF',
    description: 'Dibujá o subí tu firma y estampala en cualquier PDF. Procesamiento local, nada se sube.',
    icon: Signature,
    href: '/app/tools/pdf-sign',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'units-converter',
    name: 'Conversor de unidades',
    description: 'Longitud, peso, volumen, temperatura y moneda con tasas del Banguat en vivo.',
    icon: Calculator,
    href: '/app/tools/units-converter',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'email-signature',
    name: 'Firmas de correo',
    description: 'Plantilla de firma corporativa: el admin la define, cada quien completa sus datos y copia lista para pegar.',
    icon: MailCheck,
    href: '/app/tools/email-signature',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'admin',
    name: 'Administración',
    description: 'Panel Super Admin: organizaciones madre/afiliadas, usuarios, membresías y permisos globales.',
    icon: ShieldCheck,
    href: '/app/admin',
    requiredRoles: ['super-admin'],
    status: 'available',
  },
  {
    id: 'announcements',
    name: 'Anuncios',
    description: 'Panel corto de avisos internos con opción de notificar por correo.',
    icon: Megaphone,
    href: '/app/tools/announcements',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'ideas-board',
    name: 'Foro de ideas',
    description: 'Propuestas tipo Reddit para sistemas, Odoo, actividades y mejoras generales, con votos y comentarios.',
    icon: MessageSquareText,
    href: '/app/tools/ideas-board',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'image-ai',
    name: 'Extractor IA de documentos',
    description: 'Procesamiento de imágenes y PDFs para extraer datos con modelo vision de NVIDIA cuando esté configurado.',
    icon: ImageIcon,
    href: '/app/tools/image-ai',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'notas',
    name: 'NOTAS',
    description: 'Mini Notion interno: páginas, bloques, búsqueda rápida y base para documentación viva.',
    icon: NotebookTabs,
    href: '/app/tools/notas',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
  {
    id: 'learning',
    name: 'Learning',
    description: 'Biblioteca de aprendizaje con cursos, materiales y progreso por contenido.',
    icon: GraduationCap,
    href: '/app/tools/learning',
    requiredRoles: ['member', 'admin', 'owner'],
    status: 'available',
  },
]

export function getApp(id: string): AppDefinition | undefined {
  return apps.find((a) => a.id === id)
}

export function getAppsForRole(role: AppRole): AppDefinition[] {
  return apps.filter((a) => a.requiredRoles.includes(role))
}
